# Generated by Django 3.2.16 on 2023-02-11 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.region'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.city'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.country'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.region'),
        ),
    ]
