# Generated by Django 3.2.16 on 2023-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0002_auto_20230210_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ver_vb', models.BooleanField(default=False)),
                ('modificar_vb', models.BooleanField(default=False)),
                ('ver_contrato', models.BooleanField(default=False)),
                ('modificar_contrato', models.BooleanField(default=False)),
                ('ver_ppto', models.BooleanField(default=False)),
                ('modificar_ppto', models.BooleanField(default=False)),
                ('ver_oc', models.BooleanField(default=False)),
                ('modificar_oc', models.BooleanField(default=False)),
                ('mano_obra', models.BooleanField(default=False)),
                ('ver_cch', models.BooleanField(default=False)),
                ('modificar_cch', models.BooleanField(default=False)),
                ('ver_ccr', models.BooleanField(default=False)),
                ('modificar_ccr', models.BooleanField(default=False)),
                ('ver_ccp', models.BooleanField(default=False)),
                ('modificar_ccp', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default='Nombre Cliente', max_length=20),
        ),
    ]
