# Generated by Django 3.2.16 on 2023-02-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0002_auto_20230210_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ver_vb', models.BooleanField(default=False)),
                ('modificar_vb', models.BooleanField(default=False)),
                ('ver_contrato', models.BooleanField(default=False)),
                ('modificar_contrato', models.BooleanField(default=False)),
                ('ver_ppto', models.BooleanField(default=False)),
                ('modificar_ppto', models.BooleanField(default=False)),
                ('ver_oc', models.BooleanField(default=False)),
                ('modificar_oc', models.BooleanField(default=False)),
                ('mano_obra', models.BooleanField(default=False)),
                ('ver_cch', models.BooleanField(default=False)),
                ('modificar_cch', models.BooleanField(default=False)),
            ],
        ),
    ]
