# Generated by Django 3.2.16 on 2023-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0002_auto_20230210_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default='Nombre Cliente', max_length=20),
        ),
    ]
