# Generated by Django 3.2.16 on 2023-01-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0002_auto_20230109_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='owner',
            new_name='user',
        ),
    ]
