# Generated by Django 3.2.16 on 2023-03-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0003_auto_20230308_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
