# Generated by Django 3.2.16 on 2023-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0004_alter_proveedor_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargouser',
            name='mano_obra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='modificar_cch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='modificar_ccp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='modificar_ccr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='modificar_contrato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='modificar_ppto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='ver_cch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='ver_ccp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='ver_ccr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='ver_contrato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargouser',
            name='ver_ppto',
            field=models.BooleanField(default=False),
        ),
    ]
