# Generated by Django 3.2.16 on 2023-01-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0004_auto_20230110_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='romanNumber',
            new_name='roman_number',
        ),
    ]
