# Generated by Django 3.2.16 on 2023-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0005_rename_romannumber_region_roman_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('iso', models.SmallIntegerField()),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
