# Generated by Django 3.2.16 on 2023-01-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=50)),
                ('act', models.CharField(default='Si', max_length=2)),
                ('asu', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('diminutivo', models.CharField(max_length=3)),
                ('operacion', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9)),
                ('estado', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('act', models.CharField(default='Si', max_length=2)),
                ('usu', models.CharField(max_length=25)),
                ('par', models.BooleanField(default=0)),
                ('mat', models.BooleanField(default=0)),
                ('mau', models.IntegerField(default=0)),
                ('auo', models.BooleanField(default=0)),
                ('mon', models.BigIntegerField()),
                ('proa', models.BooleanField(default=0)),
                ('oc', models.BooleanField(default=0)),
                ('pro', models.BigIntegerField()),
                ('vis', models.BooleanField(default=0)),
                ('uf', models.FloatField()),
                ('sa', models.IntegerField(default=0)),
                ('m2', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('clasificacion', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('ccp', models.IntegerField(default=0)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('termino', models.DateTimeField()),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_administrador', to=settings.AUTH_USER_MODEL)),
                ('administrativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_administrativo', to=settings.AUTH_USER_MODEL)),
                ('compras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_compras', to=settings.AUTH_USER_MODEL)),
                ('of_tecnica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_of_tecnica', to=settings.AUTH_USER_MODEL)),
                ('prevencionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_prevencionista', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_responsable', to=settings.AUTH_USER_MODEL)),
                ('visitador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_visitador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
