# Generated by Django 3.2.16 on 2023-01-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.obra'),
        ),
    ]
