# Generated by Django 3.2.16 on 2023-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0002_contrato_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='termino',
            field=models.DateTimeField(null=True),
        ),
    ]
