# Generated by Django 3.2.16 on 2023-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='mon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pro',
            field=models.IntegerField(null=True),
        ),
    ]
