# Generated by Django 3.2.16 on 2023-01-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0005_auto_20230130_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='pro',
        ),
    ]
