# Generated by Django 3.2.16 on 2023-03-08 14:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_users', '0003_auto_20230308_1146'),
        ('hgi_static', '0007_alter_contrato_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='estado',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administrador', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_administrativo', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ccp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.clasicontrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_compras', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.estadocontrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='mau',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.obra'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='of_tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_tecnica', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='prevencionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prevencionista', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responsable', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.tipocontrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='visitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visitador', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.client'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='tipopresupuesto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hgi_users.user'),
        ),
        migrations.CreateModel(
            name='PermisoContratoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
