# Generated by Django 3.2.16 on 2023-02-14 00:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_static', '0008_auto_20230210_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoContratoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.contrato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
