# Generated by Django 3.2.16 on 2023-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0008_auto_20230210_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='estado',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ccp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='mau',
            field=models.IntegerField(default=0),
        ),
    ]
