# Generated by Django 3.2.16 on 2023-03-13 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_static', '0009_auto_20230310_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_model', models.CharField(choices=[('Contrato', 'Contrato'), ('Obra', 'Obra'), ('Oc', 'OC'), ('Cliente', 'Cliente'), ('Proveedor', 'Proveedor'), ('CajaChica', 'CajaChica'), ('Presupuesto', 'Presupuesto'), ('ProdRecurso', 'ProdRecurso'), ('ItemCC', 'ItemCC'), ('ItemRecurso', 'ItemRecurso'), ('ProductoOc', 'ProductoOc')], max_length=20, null=True)),
                ('obj_id', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
