# Generated by Django 3.2.16 on 2023-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0010_gestioncambios'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncambios',
            name='accion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
