# Generated by Django 3.2.16 on 2023-03-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0006_auto_20230322_2319'),
        ('hgi_static', '0011_gestioncambios_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.empresa'),
        ),
        migrations.AddField(
            model_name='obra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.empresa'),
        ),
    ]
