# Generated by Django 3.2.16 on 2023-01-26 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hgi_users', '0001_initial'),
        ('hgi_static', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.CharField(max_length=500)),
                ('descuento_general', models.IntegerField()),
                ('observacion', models.CharField(max_length=500)),
                ('ref_oc', models.CharField(max_length=20)),
                ('direccion_despacho', models.CharField(max_length=60)),
                ('ate_oc', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=40)),
                ('mail2', models.CharField(max_length=40)),
                ('autorizacion_adm', models.IntegerField()),
                ('autorizacion_res', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador_oc', to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emisor_oc', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.estadooc')),
                ('forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.tipopago')),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.moneda')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_users.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('tiempo', models.CharField(blank=True, max_length=5, null=True)),
                ('rfa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=400)),
                ('codigo', models.IntegerField()),
                ('sub', models.BooleanField()),
                ('rem', models.BooleanField()),
                ('pro', models.IntegerField()),
                ('pag', models.IntegerField()),
                ('arr', models.BooleanField()),
                ('rah', models.BooleanField()),
                ('cch', models.BooleanField()),
                ('man', models.BooleanField()),
                ('ope', models.IntegerField()),
                ('nco', models.CharField(max_length=3)),
                ('col', models.CharField(max_length=6)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField()),
                ('par', models.IntegerField()),
                ('mat', models.IntegerField()),
                ('afe', models.IntegerField()),
                ('ing', models.IntegerField()),
                ('cpp', models.CharField(blank=True, max_length=15, null=True)),
                ('lso', models.IntegerField()),
                ('doc', models.IntegerField()),
                ('car', models.IntegerField()),
                ('moc', models.IntegerField()),
                ('ant', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField(null=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.ordencompra')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.unidadproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.CharField(max_length=50)),
                ('pre', models.IntegerField()),
                ('prm', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('ing', models.IntegerField()),
                ('ccp', models.CharField(max_length=10)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.contrato')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.tipopresupuesto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.tipooc'),
        ),
    ]
