# Generated by Django 3.2.16 on 2023-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooc',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
    ]
