# Generated by Django 3.2.16 on 2023-01-30 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0002_alter_tipooc_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.tipooc'),
        ),
    ]
