# Generated by Django 3.2.16 on 2023-01-31 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0006_auto_20230131_0226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_ventas', '0003_alter_ordencompra_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productooc',
            name='par',
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=90, null=True)),
                ('total', models.IntegerField()),
                ('ing', models.IntegerField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('termino', models.DateTimeField(null=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_static.contrato')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productooc',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.partida'),
        ),
    ]
