# Generated by Django 3.2.16 on 2023-02-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0004_auto_20230131_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='ing',
            new_name='ingresado',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='autorizacion_adm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='autorizacion_res',
            field=models.BooleanField(default=False),
        ),
    ]
