# Generated by Django 3.2.16 on 2023-02-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0005_auto_20230203_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=50)),
                ('imputable', models.BooleanField(default=True)),
                ('asociado', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='productooc',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.recurso'),
        ),
    ]
