# Generated by Django 3.2.16 on 2023-02-09 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_ventas', '0006_auto_20230206_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='asociado',
        ),
        migrations.AddField(
            model_name='recurso',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurso',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurso_padre', to='hgi_ventas.recurso'),
        ),
        migrations.CreateModel(
            name='ProdRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('ingresado', models.IntegerField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('termino', models.DateTimeField(null=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productooc',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.prodrecurso'),
        ),
    ]
