# Generated by Django 3.2.16 on 2023-02-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0007_auto_20230208_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodrecurso',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hgi_ventas.recurso'),
        ),
    ]
