# Generated by Django 3.2.16 on 2023-02-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0010_alter_tipodocumento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_referencia', to='hgi_ventas.tipodocumento'),
        ),
    ]
