# Generated by Django 3.2.16 on 2023-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0012_auto_20230210_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ate_oc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='direccion_despacho',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='mail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='mail2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='ref_oc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
