# Generated by Django 3.2.16 on 2023-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0013_auto_20230210_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
