# Generated by Django 3.2.16 on 2023-02-11 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_users', '0002_auto_20230210_2154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_static', '0008_auto_20230210_2153'),
        ('hgi_ventas', '0014_ordencompra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.estadocajachica'),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.ordencompra'),
        ),
        migrations.AlterField(
            model_name='estadocajachica',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='caja_chica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.cajachica'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.partida'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.proveedor'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.prodrecurso'),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='itemrecurso',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='itemrecurso',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='itemrecurso',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.partida'),
        ),
        migrations.AlterField(
            model_name='itemrecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.prodrecurso'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_oc', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor_oc', to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.estadooc'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.tipopago'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.moneda'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.proveedor'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.tipooc'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_static.tipopresupuesto'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='prodrecurso',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='prodrecurso',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.partida'),
        ),
        migrations.AlterField(
            model_name='prodrecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.recurso'),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.partida'),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.prodrecurso'),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.unidadproducto'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurso_padre', to='hgi_ventas.recurso'),
        ),
        migrations.AlterField(
            model_name='tipooc',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_users.user'),
        ),
    ]
