# Generated by Django 3.2.16 on 2023-03-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0009_auto_20230310_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hgi_ventas', '0014_auto_20230308_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hgi_static.contrato'),
        ),
        migrations.AlterField(
            model_name='estadocajachica',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemrecurso',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='creador_oc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='emisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='emisor_oc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partida',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prodrecurso',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipooc',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
