# Generated by Django 3.2.16 on 2023-02-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0015_auto_20230210_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.ordencompra'),
        ),
    ]
