# Generated by Django 3.2.16 on 2023-03-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0015_auto_20230310_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodrecurso',
            name='ingresado',
        ),
    ]
