# Generated by Django 3.2.16 on 2023-03-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_static', '0009_auto_20230308_1117'),
        ('hgi_ventas', '0016_alter_cajachica_oc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='ingresado',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='ing',
        ),
        migrations.AddField(
            model_name='itemcajachica',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='aut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.estadocajachica'),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcajachica',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='hgi_static.estadooc'),
        ),
    ]
