# Generated by Django 3.2.16 on 2023-03-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0016_remove_prodrecurso_ingresado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productooc',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.recurso'),
        ),
    ]
