# Generated by Django 3.2.16 on 2023-02-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgi_ventas', '0016_alter_cajachica_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcajachica',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgi_ventas.recurso'),
        ),
    ]
